### ISSUE TITLE
Marginalia chokes on Clojure 1.7 with deeper-level namespaces

### ISSUE THREAD

**Issue by eigenhombre** [gdeer81/lein-marginalia#17]
Steps to reproduce:

    lein new marg17
    cd marg17
    mkdir sub

In `marg17/sub/a.clj`:

    (ns marg17.sub.a)

In `marg17/sub/b.clj`:

    (ns marg17.sub.b
      (:require [marg17.sub.a]))

In `project.clj`: change Clojure 1.6 to 1.7.

Result:

    marg17 (master)  lein marg
    Generating Marginalia documentation for the following source files:
       /Users/jjacobsen/ol-dev/ng-salt/dev2/projects/marg17/src/marg17/core.clj
       /Users/jjacobsen/ol-dev/ng-salt/dev2/projects/marg17/src/marg17/sub/a.clj
       /Users/jjacobsen/ol-dev/ng-salt/dev2/projects/marg17/src/marg17/sub/b.clj

    Exception in thread "main" java.lang.RuntimeException: Problem parsing near line 1 <require [marg17.sub.a]))> original reported cause is clojure.lang.ArityException: Wrong number of args (4) passed to: parser/read-keyword -- clojure.lang.ArityException: Wrong number of args (4) passed to: parser/read-keyword, compiling:(/private/var/folders/qt/x00tk_5100d9vv6p3ffldy740000gp/T/form-init3410464737499441527.clj:1:125)
	    at clojure.lang.Compiler.load(Compiler.java:7239)
	    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	    at clojure.main$load_script.invoke(main.clj:275)
	    at clojure.main$init_opt.invoke(main.clj:280)
	    at clojure.main$initialize.invoke(main.clj:308)
	    at clojure.main$null_opt.invoke(main.clj:343)
	    at clojure.main$main.doInvoke(main.clj:421)
	    at clojure.lang.RestFn.invoke(RestFn.java:421)
	    at clojure.lang.Var.invoke(Var.java:383)
	    at clojure.lang.AFn.applyToHelper(AFn.java:156)
	    at clojure.lang.Var.applyTo(Var.java:700)
	    at clojure.main.main(main.java:37)
    Caused by: java.lang.RuntimeException: Problem parsing near line 1 <require [marg17.sub.a]))> original reported cause is clojure.lang.ArityException: Wrong number of args (4) passed to: parser/read-keyword -- clojure.lang.ArityException: Wrong number of args (4) passed to: parser/read-keyword
	    at clojure.lang.LispReader.read(LispReader.java:292)
	    at clojure.lang.LispReader.read(LispReader.java:196)
	    at clojure.lang.LispReader.read(LispReader.java:190)
	    at marginalia.parser$parse_STAR_$fn__418$fn__421.invoke(parser.clj:153)
	    at marginalia.parser$parse_STAR_$fn__418.invoke(parser.clj:152)
	    at clojure.core$repeatedly$fn__5111.invoke(core.clj:4921)
	    at clojure.lang.LazySeq.sval(LazySeq.java:40)
	    at clojure.lang.LazySeq.seq(LazySeq.java:49)
	    at clojure.lang.RT.seq(RT.java:507)
	    at clojure.core$seq__4128.invoke(core.clj:137)
	    at clojure.core$tree_seq$walk__5045$fn__5046.invoke(core.clj:4739)
	    at clojure.lang.LazySeq.sval(LazySeq.java:40)
	    at clojure.lang.LazySeq.seq(LazySeq.java:49)
	    at clojure.lang.LazySeq.more(LazySeq.java:85)
	    at clojure.lang.RT.more(RT.java:683)
	    at clojure.core$rest__4114.invoke(core.clj:73)
	    at clojure.core$flatten.invoke(core.clj:6851)
	    at marginalia.parser$parse_STAR_.invoke(parser.clj:146)
	    at marginalia.parser$parse.invoke(parser.clj:382)
	    at marginalia.parser$parse_file.invoke(parser.clj:400)
	    at marginalia.core$path_to_doc.invoke(core.clj:177)
	    at clojure.core$map$fn__4553.invoke(core.clj:2624)
	    at clojure.lang.LazySeq.sval(LazySeq.java:40)
	    at clojure.lang.LazySeq.seq(LazySeq.java:49)
	    at clojure.lang.RT.seq(RT.java:507)
	    at clojure.core$seq__4128.invoke(core.clj:137)
	    at clojure.core$map$fn__4553.invoke(core.clj:2616)
	    at clojure.lang.LazySeq.sval(LazySeq.java:40)
	    at clojure.lang.LazySeq.seq(LazySeq.java:49)
	    at clojure.lang.RT.seq(RT.java:507)
	    at clojure.core$seq__4128.invoke(core.clj:137)
	    at clojure.core$map$fn__4553.invoke(core.clj:2616)
	    at clojure.lang.LazySeq.sval(LazySeq.java:40)
	    at clojure.lang.LazySeq.seq(LazySeq.java:49)
	    at clojure.lang.Cons.next(Cons.java:39)
	    at clojure.lang.RT.boundedLength(RT.java:1735)
	    at clojure.lang.RestFn.applyTo(RestFn.java:130)
	    at clojure.core$apply.invoke(core.clj:630)
	    at marginalia.hiccup$eval57$fn__58.invoke(hiccup.clj:99)
	    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	    at clojure.lang.Var.invoke(Var.java:379)
	    at marginalia.html$toc_html.invoke(html.clj:189)
	    at marginalia.html$uberdoc_html.invoke(html.clj:400)
	    at marginalia.core$uberdoc_BANG_.invoke(core.clj:208)
	    at marginalia.core$run_marginalia.doInvoke(core.clj:293)
	    at clojure.lang.RestFn.invoke(RestFn.java:410)
	    at user$eval792.invoke(form-init3410464737499441527.clj:1)
	    at clojure.lang.Compiler.eval(Compiler.java:6782)
	    at clojure.lang.Compiler.eval(Compiler.java:6772)
	    at clojure.lang.Compiler.load(Compiler.java:7227)
	    ... 11 more
    Subprocess failed
    marg17 (master)

Change it back to 1.6.0 and it works fine.

**Comment by eigenhombre** [comment]
Upon reflection this should probably be filed against Marginalia proper.
