### ISSUE TITLE
Parsing error: Wrong number of args (4) passed to: parser/read-keyword

### ISSUE THREAD

**Issue by davidplumpton** [gdeer81/lein-marginalia#19]
Using clojure 1.8 and marginalia 0.8.0 I get the following error when I run "lein marge" on my project https://github.com/davidplumpton/homeworldsai

Exception in thread "main" java.lang.RuntimeException: Problem parsing near line 1 <gen-class))> original reported cause is clojure.lang.ArityException: Wrong number of args (4)
passed to: parser/read-keyword -- clojure.lang.ArityException: Wrong number of args (4) passed to: parser/read-keyword, compiling:(/private/var/folders/h_/tj7s1cyn0wb49fcnhc660gb
w1b_4z4/T/form-init5895226127987567712.clj:1:125)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Problem parsing near line 1 <gen-class))> original reported cause is clojure.lang.ArityException: Wrong number of args (4) passed to: parse
r/read-keyword -- clojure.lang.ArityException: Wrong number of args (4) passed to: parser/read-keyword
        at clojure.lang.LispReader.read(LispReader.java:292)
        at clojure.lang.LispReader.read(LispReader.java:196)
        at clojure.lang.LispReader.read(LispReader.java:190)
        at marginalia.parser$parse_STAR_$fn__422$fn__425.invoke(parser.clj:153)
        at marginalia.parser$parse_STAR_$fn__422.invoke(parser.clj:152)
        at clojure.core$repeatedly$fn__5339.invoke(core.clj:4945)

**Comment by davidplumpton** [comment]
Duplicate of https://github.com/gdeer81/marginalia/issues/158
